---
driver:
  name: vagrant
  customize:
    memory: 2048
  synced_folders:
    - ['.', '/opt/tarantool_cloud']
    - ['test/shared/ca', '/var/tarantool_cloud/ca']

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
      image: ubuntu-16-04-x64

provisioner:
  name: puppet_apply
  manifests_path: puppet/manifests
  modules_path: puppet/modules
  hiera_config_path: puppet/hiera.yaml
  hiera_data_path: puppet/hieradata
  require_chef_for_busser: false
  require_puppet_collections: true
  puppet_apt_collections_repo: http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb
  puppetfile_path: puppet/Puppetfile
  puppet_debug: true
  puppet_verbose: true

suites:
  - name: node1
    driver:
      vm_hostname: node1
    provisioner:
      manifest: default.pp
      custom_facts:
        nodename: node1
        external_ip: 172.16.20.12
    driver:
      network:
        - ["private_network", {ip: "172.16.20.12"}]
  - name: node2
    driver:
      vm_hostname: node2
    provisioner:
      manifest: default.pp
      custom_facts:
        nodename: node2
        external_ip: 172.16.20.13
    driver:
      network:
        - ["private_network", {ip: "172.16.20.13"}]
  - name: node3
    driver:
      vm_hostname: node3
    provisioner:
      manifest: default.pp
      custom_facts:
        nodename: node3
        external_ip: 172.16.20.14

    driver:
      network:
        - ["private_network", {ip: "172.16.20.14"}]
  - name: node4
    driver:
      vm_hostname: node4
    provisioner:
      manifest: default.pp
      custom_facts:
        nodename: node4
        external_ip: 172.16.20.15

    driver:
      network:
        - ["private_network", {ip: "172.16.20.15"}]
