---
driver:
  name: vagrant
  customize:
    memory: 2048
  synced_folders:
    - ['.', '/opt/tarantool_cloud']
    - ['test/shared/ca', '/var/tarantool_cloud/ca']

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
      image: ubuntu-16-04-x64

provisioner:
  name: puppet_apply
  manifests_path: puppet/manifests
  modules_path: modules
  #hiera_config_path: puppet/hiera.yaml
  hiera_data_path: puppet/hieradata
  require_chef_for_busser: false
  require_puppet_collections: true
  puppet_apt_collections_repo: http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb
  puppetfile_path: puppet/Puppetfile

suites:
  - name: node1
    provisioner:
      manifest: default.pp
  - name: node2
    provisioner:
      manifest: default.pp
  - name: node3
    provisioner:
      manifest: default.pp
