version: '2'
services:
  # Instances to run cloud containers
  docker1:
    image: docker:dind
    privileged: true

  consul1:
    image: consul
    links:
      - docker1
    ports:
      - "8500:8500"
    tmpfs: /tmp/consul
    environment:
      CONSUL_LOCAL_CONFIG: |
        {
          "services": [{
            "name": "docker",
            "address": "docker1",
            "port": 2375,
            "tags": ["lb_group=primary"],
            "checks": [
              {
                "http": "http://docker1:2375/_ping",
                "interval": "5s"
              }
            ]
          }]
        }
      DOCKER_HOST: tcp://docker1:2375
    command: agent -server -bootstrap-expect=1 -ui -client 0.0.0.0

  api:
    build: .
    links:
      - consul1
    ports:
      - "5061:5061"
    environment:
      CONSUL_HOST: "consul1"
      LISTEN_PORT: 5061
      IPALLOC_RANGE: 172.55.128.0/25
      GATEWAY_IP: 172.55.128.1
      DOCKER_NETWORK: mynet
      CREATE_NETWORK_AUTOMATICALLY: "true"
