---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Add primary tarantool yum repo
    copy:
      src=tarantool_1_6.repo
      dest=/etc/yum.repos.d/
      owner=root group=root mode=0644

  - name: Add docker yum repo
    copy:
      src=docker.repo
      dest=/etc/yum.repos.d/
      owner=root group=root mode=0644

  - name: NGINX | Installing NGINX repo rpm
    yum:
      name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm

  # work around rpm dependency problem
  - name: install lvm2
    yum: name=lvm2 state=latest

  - name: install docker
    yum: name=docker-engine state=latest

  - name: Install git
    yum: name=git state=latest

  - name: Install gcc
    yum: name=gcc state=latest

  - name: Install cmake
    yum: name=cmake state=latest

  - name: Install tarantool server
    yum: name=tarantool state=latest

  - name: Install tarantool memcached
    yum: name=tarantool-memcached state=latest

  - name: Install tarantool http
    yum: name=tarantool-http state=latest

  - name: Install nginx
    yum: name=nginx state=latest

  - name: Install pcre-devel
    yum: name=pcre-devel state=latest

  - name: Install zlib-devel
    yum: name=zlib-devel state=latest

  - name: nginx dependencies
    yum: state=latest name={{ item }}
    with_items:
      - openssl-devel
      - libaio-devel
      - libxslt-devel
      - gd-devel
      - perl-ExtUtils-Embed
      - perl-devel
      - GeoIP-devel

  - name: check out tarantool nginx module
    git:
      repo=https://github.com/racktear/nginx_upstream_module.git
      dest=/opt/src/tarantool-nginx-module
      version=dynamic-modules-build-fix
      force=yes

  - name: check out nginx source
    git:
      repo=https://github.com/nginx/nginx.git
      dest=/opt/src/tarantool-nginx-module/nginx
      version=release-1.10.0
      force=yes

  - name: check out tarantool cloud source
    git:
      repo=https://github.com/tarantool/cloud.git
      dest=/opt/tarantool/cloud
      version=master
      force=yes
    when: localdeploy is undefined

  - name: build tarantool nginx module
    shell: |
      make yajl
      cd /opt/src/tarantool-nginx-module/nginx
      flags=$(nginx -V 2>&1 | sed -n -e 's/^configure arguments: \(.*\)$/\1/p' | sed 's/--add-dynamic-module=[^ ]*//g')
      eval "./auto/configure --add-dynamic-module='/opt/src/tarantool-nginx-module' $flags"
      make -f objs/Makefile
    args:
      chdir: /opt/src/tarantool-nginx-module

  - name: install tarantool nginx module
    command: >
      mv /opt/src/tarantool-nginx-module/nginx/objs/ngx_http_tnt_module.so \
         /usr/lib64/nginx/modules/

  - file: path=/etc/nginx/conf.d/default.conf state=absent
  - name: copy tarantool nginx configuration file
    copy:
      src=tarantool_cloud.conf
      dest=/etc/nginx/conf.d
      owner=root group=root mode=0644
  - name: copy main nginx configuration file
    copy:
      src=nginx.conf
      dest=/etc/nginx
      owner=root group=root mode=0644


  - service: name=nginx enabled=yes state=restarted
  - service: name=docker enabled=yes state=restarted

  - name: build tarantool docker image
    command: >
      docker build -t memcached .
    args:
      chdir: /opt/tarantool/cloud/docker

  - name: set up custom docker network
    shell: >
      if [[ -z "$(docker network ls -f 'name=customnet' -q)" ]];
      then
          docker network create --driver bridge --subnet="172.18.0.0/16" --gateway="172.18.0.1" customnet;
      fi

  - name: set up cloud service
    copy:
      src=tarantool_cloud.lua
      dest=/etc/tarantool/instances.available/tarantool_cloud.lua
      owner=root group=root mode=0644

  - name: add systemd init file for cloud service
    copy:
      src=tarantool_cloud.service
      dest=/usr/lib/systemd/system/tarantool_cloud.service
      owner=root group=root mode=0644

  - name: set tarantool to run as root
    copy:
      src=tarantool.sysconfig
      dest=/etc/sysconfig/tarantool
      owner=root group=root mode=0644


  - service: name=tarantool_cloud enabled=yes state=restarted
